### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by davidgs** [atomicmooseca/pine64-gt9xxf_ts#1]
make -C /lib/modules/3.10.104/build M=/home/ubuntu/pine64-gt9xxf_ts modules
make[1]: Entering directory '/lib/modules/3.10.104/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/lib/modules/3.10.104/build'
Makefile:11: recipe for target 'all' failed

There seems to be no /lib/modules/<version>/build directory,

**Comment by atomicmooseca** [comment]
This patch was made for Pine64 Debian, not Ubuntu.
